name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, sqlite

      - name: Install Composer dependencies
        working-directory: ./laravel-ci-cd
        run: composer install --no-progress --prefer-dist

      - name: Generate Laravel application key
        working-directory: ./laravel-ci-cd
        run: php artisan key:generate

      - name: Run Tests
        working-directory: ./laravel-ci-cd
        run: php artisan test

      - name: Simulate deployment
        run: echo "Deploying Laravel app..."
