name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Simulate deployment
        run: echo "Deploying Laravel app to production..."
